version: "3.9"

# TODO: change so it can run after local development.

services:
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "${DB_HOST_IP}:${DB_HOST_PORT}:5432"

  backend:
    build: ./backend
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    env_file:
      - backend-variables.env
    ports:
      - "${BACKEND_HOST_IP}:${BACKEND_HOST_PORT}:8000"
    # Waits until database is ready before running backend command.
    command: sh -c "wait-for db:5432 -- gunicorn myproject.wsgi -b 127.0.0.1:8001"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_HOST_IP}:${FRONTEND_HOST_PORT}:5000"
    command: sh -c "yarn build && yarn serve -s -n build"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
