version: "3.9"

services:
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "${DB_HOST_IP}:${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
  backend:
    build: ./backend
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    env_file:
      - backend-variables.env
    command: ${BACKEND_COMMAND}
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_HOST_IP}:${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    depends_on:
      - db
