version: "3.9"

services:
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "${DB_HOST_IP}:${DB_HOST_PORT}:5432"
  backend:
    build: ./backend
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    env_file:
      - backend-variables.env
    command: ${BACKEND_COMMAND}
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_HOST_IP}:${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: yarn start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend
